-- MoonCen integrated Ops Console core schema.
--
-- This repository uses immutable, checksummed SQL migrations through
-- DB/setup_db.py.  Do not edit this file after it has been applied; add a new
-- versioned migration instead.

CREATE TABLE ops_agents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    hostname TEXT NOT NULL,
    environment TEXT NOT NULL,
    os_type TEXT NOT NULL,
    ip_address INET,
    version TEXT,
    status TEXT NOT NULL DEFAULT 'unknown',
    capabilities JSONB NOT NULL DEFAULT '[]'::jsonb,
    credential_hint TEXT,
    maintenance_mode BOOLEAN NOT NULL DEFAULT false,
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ops_agents_environment
        CHECK (environment IN ('production', 'staging', 'development')),
    CONSTRAINT chk_ops_agents_status
        CHECK (status IN ('healthy', 'warning', 'critical', 'unknown', 'disabled')),
    CONSTRAINT chk_ops_agents_capabilities_array
        CHECK (jsonb_typeof(capabilities) = 'array'),
    CONSTRAINT ux_ops_agents_environment_hostname UNIQUE (environment, hostname)
);

CREATE TABLE ops_services (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id UUID REFERENCES ops_agents(id) ON DELETE SET NULL,
    service_name TEXT NOT NULL,
    service_type TEXT NOT NULL,
    environment TEXT NOT NULL,
    health_url TEXT,
    grafana_url TEXT,
    current_version TEXT,
    current_commit TEXT,
    status TEXT NOT NULL DEFAULT 'unknown',
    response_time_ms INTEGER,
    last_error TEXT,
    dependencies JSONB NOT NULL DEFAULT '[]'::jsonb,
    last_checked_at TIMESTAMPTZ,
    last_restarted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ops_services_type
        CHECK (service_type IN (
            'frontend', 'backend', 'database', 'redis', 'crawler',
            'ai_worker', 'agent', 'proxy', 'scheduler'
        )),
    CONSTRAINT chk_ops_services_environment
        CHECK (environment IN ('production', 'staging', 'development')),
    CONSTRAINT chk_ops_services_status
        CHECK (status IN ('healthy', 'warning', 'critical', 'unknown', 'disabled')),
    CONSTRAINT chk_ops_services_response_time
        CHECK (response_time_ms IS NULL OR response_time_ms >= 0),
    CONSTRAINT chk_ops_services_dependencies_array
        CHECK (jsonb_typeof(dependencies) = 'array'),
    CONSTRAINT ux_ops_services_environment_name UNIQUE (environment, service_name)
);

CREATE TABLE ops_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    environment TEXT NOT NULL,
    agent_id UUID REFERENCES ops_agents(id) ON DELETE SET NULL,
    service_id UUID REFERENCES ops_services(id) ON DELETE SET NULL,
    parent_job_id UUID REFERENCES ops_jobs(id) ON DELETE SET NULL,
    requested_by UUID REFERENCES users(id) ON DELETE SET NULL,
    target_key TEXT,
    deduplication_key TEXT,
    parameters JSONB NOT NULL DEFAULT '{}'::jsonb,
    progress INTEGER NOT NULL DEFAULT 0,
    result JSONB,
    error_code TEXT,
    error_message TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retries INTEGER NOT NULL DEFAULT 0,
    queued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    heartbeat_at TIMESTAMPTZ,
    cancel_requested_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ops_jobs_type
        CHECK (job_type IN (
            'crawler_run', 'crawler_retry', 'service_restart',
            'service_health_check', 'deployment', 'rollback',
            'database_backup', 'database_restore', 'database_migration',
            'cache_clear', 'log_collect', 'data_quality_scan',
            'address_fix', 'content_update', 'agent_command'
        )),
    CONSTRAINT chk_ops_jobs_status
        CHECK (status IN (
            'queued', 'assigned', 'running', 'success', 'failed',
            'cancelled', 'timed_out', 'blocked'
        )),
    CONSTRAINT chk_ops_jobs_environment
        CHECK (environment IN ('production', 'staging', 'development')),
    CONSTRAINT chk_ops_jobs_progress CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT chk_ops_jobs_retries
        CHECK (retry_count >= 0 AND max_retries BETWEEN 0 AND 20),
    CONSTRAINT chk_ops_jobs_parameters_object
        CHECK (jsonb_typeof(parameters) = 'object'),
    CONSTRAINT chk_ops_jobs_result_object
        CHECK (result IS NULL OR jsonb_typeof(result) = 'object')
);

CREATE UNIQUE INDEX ux_ops_jobs_active_deduplication
    ON ops_jobs (deduplication_key)
    WHERE deduplication_key IS NOT NULL
      AND btrim(deduplication_key) <> ''
      AND status IN ('queued', 'assigned', 'running');
CREATE INDEX idx_ops_jobs_status_queued
    ON ops_jobs (status, queued_at);
CREATE INDEX idx_ops_jobs_requested_created
    ON ops_jobs (requested_by, created_at DESC);
CREATE INDEX idx_ops_jobs_agent_status
    ON ops_jobs (agent_id, status, queued_at);
CREATE INDEX idx_ops_jobs_parent
    ON ops_jobs (parent_job_id);

CREATE TABLE ops_job_logs (
    id BIGSERIAL PRIMARY KEY,
    job_id UUID NOT NULL REFERENCES ops_jobs(id) ON DELETE CASCADE,
    log_level TEXT NOT NULL DEFAULT 'info',
    message TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ops_job_logs_level
        CHECK (log_level IN ('debug', 'info', 'warning', 'error')),
    CONSTRAINT chk_ops_job_logs_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX idx_ops_job_logs_job_created
    ON ops_job_logs (job_id, created_at, id);

CREATE TABLE ops_deployments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id UUID NOT NULL UNIQUE REFERENCES ops_jobs(id) ON DELETE RESTRICT,
    environment TEXT NOT NULL,
    service_type TEXT NOT NULL,
    previous_version TEXT,
    target_version TEXT NOT NULL,
    previous_commit TEXT,
    target_commit TEXT NOT NULL,
    branch TEXT,
    deployment_status TEXT NOT NULL DEFAULT 'queued',
    health_check_result JSONB,
    smoke_test_result JSONB,
    rollback_deployment_id UUID REFERENCES ops_deployments(id) ON DELETE SET NULL,
    requested_by UUID REFERENCES users(id) ON DELETE SET NULL,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ops_deployments_environment
        CHECK (environment IN ('production', 'staging', 'development')),
    CONSTRAINT chk_ops_deployments_service_type
        CHECK (service_type IN ('frontend', 'backend', 'crawler', 'agent', 'scheduler', 'full')),
    CONSTRAINT chk_ops_deployments_status
        CHECK (deployment_status IN (
            'queued', 'running', 'success', 'failed', 'cancelled',
            'rolling_back', 'rolled_back', 'blocked'
        ))
);

CREATE INDEX idx_ops_deployments_environment_created
    ON ops_deployments (environment, created_at DESC);

CREATE TABLE ops_audit_logs (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT,
    ip_address INET,
    user_agent TEXT,
    before_data JSONB,
    after_data JSONB,
    result TEXT NOT NULL,
    job_id UUID REFERENCES ops_jobs(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ops_audit_logs_result
        CHECK (result IN ('success', 'failed', 'blocked')),
    CONSTRAINT chk_ops_audit_before_object
        CHECK (before_data IS NULL OR jsonb_typeof(before_data) = 'object'),
    CONSTRAINT chk_ops_audit_after_object
        CHECK (after_data IS NULL OR jsonb_typeof(after_data) = 'object')
);

CREATE INDEX idx_ops_audit_logs_created
    ON ops_audit_logs (created_at DESC);
CREATE INDEX idx_ops_audit_logs_user_created
    ON ops_audit_logs (user_id, created_at DESC);
CREATE INDEX idx_ops_audit_logs_resource
    ON ops_audit_logs (resource_type, resource_id, created_at DESC);
CREATE INDEX idx_ops_audit_logs_job
    ON ops_audit_logs (job_id);

CREATE TABLE ops_alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    severity TEXT NOT NULL,
    alert_type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    resource_type TEXT,
    resource_id TEXT,
    status TEXT NOT NULL DEFAULT 'open',
    detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    acknowledged_by UUID REFERENCES users(id) ON DELETE SET NULL,
    acknowledged_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ops_alerts_severity
        CHECK (severity IN ('info', 'warning', 'critical')),
    CONSTRAINT chk_ops_alerts_status
        CHECK (status IN ('open', 'acknowledged', 'resolved', 'ignored')),
    CONSTRAINT chk_ops_alerts_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX idx_ops_alerts_status_severity
    ON ops_alerts (status, severity, detected_at DESC);

CREATE TABLE ops_crawler_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    crawler_name TEXT NOT NULL,
    content_type TEXT NOT NULL,
    provider TEXT,
    branch TEXT,
    source_url TEXT,
    current_stage TEXT,
    agent_id UUID REFERENCES ops_agents(id) ON DELETE SET NULL,
    job_id UUID UNIQUE REFERENCES ops_jobs(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    run_mode TEXT NOT NULL DEFAULT 'apply',
    total_count INTEGER NOT NULL DEFAULT 0,
    processed_count INTEGER NOT NULL DEFAULT 0,
    success_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    new_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    deleted_candidate_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ops_crawler_runs_content_type
        CHECK (content_type IN ('culture_center', 'experience', 'education', 'all')),
    CONSTRAINT chk_ops_crawler_runs_status
        CHECK (status IN (
            'idle', 'queued', 'running', 'success', 'partial_success',
            'failed', 'stopping', 'disabled', 'cancelled', 'blocked'
        )),
    CONSTRAINT chk_ops_crawler_runs_mode
        CHECK (run_mode IN ('apply', 'dry_run', 'review')),
    CONSTRAINT chk_ops_crawler_runs_counts
        CHECK (
            total_count >= 0 AND processed_count >= 0 AND success_count >= 0
            AND failed_count >= 0 AND new_count >= 0 AND updated_count >= 0
            AND deleted_candidate_count >= 0
        )
);

CREATE INDEX idx_ops_crawler_runs_created
    ON ops_crawler_runs (created_at DESC);
CREATE INDEX idx_ops_crawler_runs_provider_created
    ON ops_crawler_runs (provider, created_at DESC);
CREATE INDEX idx_ops_crawler_runs_status_created
    ON ops_crawler_runs (status, created_at DESC);

CREATE TABLE ops_crawler_errors (
    id BIGSERIAL PRIMARY KEY,
    crawler_run_id UUID NOT NULL REFERENCES ops_crawler_runs(id) ON DELETE CASCADE,
    error_type TEXT NOT NULL,
    provider TEXT,
    branch TEXT,
    source_url TEXT,
    message TEXT NOT NULL,
    stack_trace TEXT,
    screenshot_path TEXT,
    html_path TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    resolved BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ops_crawler_errors_type
        CHECK (error_type IN (
            'network_error', 'timeout', 'http_error', 'browser_error',
            'selector_error', 'parsing_error', 'validation_error',
            'database_error', 'duplicate_error', 'unknown_error'
        )),
    CONSTRAINT chk_ops_crawler_errors_retry CHECK (retry_count >= 0)
);

CREATE INDEX idx_ops_crawler_errors_run_created
    ON ops_crawler_errors (crawler_run_id, created_at DESC);
CREATE INDEX idx_ops_crawler_errors_unresolved
    ON ops_crawler_errors (resolved, created_at DESC);

CREATE TABLE ops_quality_issues (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    issue_key TEXT,
    issue_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    content_type TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT,
    provider TEXT,
    branch TEXT,
    field_name TEXT,
    current_value JSONB,
    previous_value JSONB,
    status TEXT NOT NULL DEFAULT 'open',
    assigned_to UUID REFERENCES users(id) ON DELETE SET NULL,
    auto_fixable BOOLEAN NOT NULL DEFAULT false,
    blocked_sync BOOLEAN NOT NULL DEFAULT false,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_by UUID REFERENCES users(id) ON DELETE SET NULL,
    resolved_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ops_quality_severity
        CHECK (severity IN ('info', 'warning', 'critical')),
    CONSTRAINT chk_ops_quality_content_type
        CHECK (content_type IN ('culture_center', 'experience', 'education', 'unknown')),
    CONSTRAINT chk_ops_quality_status
        CHECK (status IN ('open', 'reviewing', 'resolved', 'ignored', 'auto_fixed')),
    CONSTRAINT chk_ops_quality_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE UNIQUE INDEX ux_ops_quality_active_issue_key
    ON ops_quality_issues (issue_key)
    WHERE issue_key IS NOT NULL
      AND btrim(issue_key) <> ''
      AND status IN ('open', 'reviewing');
CREATE INDEX idx_ops_quality_status_severity
    ON ops_quality_issues (status, severity, detected_at DESC);
CREATE INDEX idx_ops_quality_provider_detected
    ON ops_quality_issues (provider, detected_at DESC);
CREATE INDEX idx_ops_quality_resource
    ON ops_quality_issues (resource_type, resource_id);

CREATE TABLE ops_content_overrides (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    resource_type TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    field_name TEXT NOT NULL,
    source_value JSONB,
    normalized_value JSONB,
    manual_value JSONB,
    is_locked BOOLEAN NOT NULL DEFAULT false,
    updated_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_ops_content_override_field
        UNIQUE (resource_type, resource_id, field_name)
);

CREATE INDEX idx_ops_content_overrides_resource
    ON ops_content_overrides (resource_type, resource_id);

COMMENT ON TABLE ops_jobs IS
    'PostgreSQL-backed Ops job queue; workers claim rows with FOR UPDATE SKIP LOCKED.';
COMMENT ON COLUMN ops_jobs.deduplication_key IS
    'Stable server-generated key preventing concurrent duplicate mutations.';
COMMENT ON COLUMN ops_agents.credential_hint IS
    'Non-secret identifier only. Agent API keys and certificates are never stored in plaintext here.';
