# Generated by tools/generate_registry_crawler_files.py; DO NOT EDIT.
from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional, Sequence


PROVIDER = "SUWON_LIBRARY_MV"
ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from Crawler.Crawler_GeneratedYamlTargets import main  # noqa: E402


def run(argv: Optional[Sequence[str]] = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if any(arg == "--all" or arg == "--write-registry" or arg.startswith("--provider") for arg in args):
        raise SystemExit(f"{PROVIDER} wrapper has a fixed provider; provider/all/registry overrides are not permitted")
    return main(["--provider", PROVIDER, *args])


if __name__ == "__main__":
    raise SystemExit(run())
