apiVersion: 1

contactPoints:
  - orgId: 1
    name: mooncen-telegram
    receivers:
      - uid: mooncen_telegram
        type: telegram
        disableResolveMessage: false
        settings:
          bottoken: ${GRAFANA_TELEGRAM_BOT_TOKEN}
          chatid: $GRAFANA_TELEGRAM_CHAT_ID_JSON
          message: |
            {{ template "mooncen.telegram.message" . }}
