from __future__ import annotations

import hashlib
import os
import re
import shlex
import tempfile
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
REGISTRY_FILE = ROOT / "config" / "generated_yaml_crawler_registry.yaml"
OUTPUT_DIR = ROOT / "Crawler" / "generated_yaml"
MANIFEST_FILE = OUTPUT_DIR / ".generated_wrappers.yaml"
MANIFEST_VERSION = 1


PROVIDER_PATTERN = re.compile(r"[A-Z][A-Z0-9_]{0,49}\Z")


class UniqueKeyLoader(yaml.SafeLoader):
    pass


def _construct_unique_mapping(loader: UniqueKeyLoader, node: yaml.MappingNode, deep: bool = False) -> dict[Any, Any]:
    loader.flatten_mapping(node)
    mapping: dict[Any, Any] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        if key in mapping:
            raise ValueError(f"Duplicate YAML mapping key: {key!r}")
        mapping[key] = loader.construct_object(value_node, deep=deep)
    return mapping


UniqueKeyLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, _construct_unique_mapping)


MANAGED_HEADER = "# Generated by tools/generate_registry_crawler_files.py; DO NOT EDIT."


WRAPPER_TEMPLATE = '''# Generated by tools/generate_registry_crawler_files.py; DO NOT EDIT.
from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional, Sequence


PROVIDER = "{provider}"
ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from Crawler.Crawler_GeneratedYamlTargets import main  # noqa: E402


def run(argv: Optional[Sequence[str]] = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if any(arg == "--all" or arg == "--write-registry" or arg.startswith("--provider") for arg in args):
        raise SystemExit(f"{{PROVIDER}} wrapper has a fixed provider; provider/all/registry overrides are not permitted")
    return main(["--provider", PROVIDER, *args])


if __name__ == "__main__":
    raise SystemExit(run())
'''


def safe_module_name(provider: str) -> str:
    name = str(provider).strip().upper()
    if not PROVIDER_PATTERN.fullmatch(name):
        raise ValueError(f"Invalid provider identifier: {name!r}")
    return name


def is_managed_wrapper_content(content: str) -> bool:
    if not content.startswith(f"{MANAGED_HEADER}\n"):
        return False
    match = re.search(r'^PROVIDER = "([A-Z][A-Z0-9_]{0,49})"$', content, flags=re.MULTILINE)
    return bool(match and content == WRAPPER_TEMPLATE.format(provider=match.group(1)))


def is_managed_wrapper(path: Path) -> bool:
    if path.name == "__init__.py" or not path.is_file():
        return False
    try:
        return is_managed_wrapper_content(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError):
        return False


def load_manifest(path: Path = MANIFEST_FILE) -> dict[str, dict[str, str]]:
    if not path.exists():
        return {}
    data = yaml.load(path.read_text(encoding="utf-8"), Loader=UniqueKeyLoader) or {}  # noqa: S506
    if not isinstance(data, dict) or data.get("version") != MANIFEST_VERSION or not isinstance(data.get("wrappers"), list):
        raise ValueError(f"Invalid generated wrapper manifest: {path}")
    entries: dict[str, dict[str, str]] = {}
    for index, entry in enumerate(data["wrappers"], start=1):
        if not isinstance(entry, dict):
            raise ValueError(f"{path}:{index}: manifest entry must be a mapping")
        provider = safe_module_name(entry.get("provider", ""))
        filename = str(entry.get("file") or "")
        digest = str(entry.get("sha256") or "")
        if filename != f"{provider}.py" or not re.fullmatch(r"[0-9a-f]{64}", digest):
            raise ValueError(f"{path}:{index}: invalid manifest entry")
        if provider in entries:
            raise ValueError(f"{path}:{index}: duplicate manifest provider {provider}")
        entries[provider] = {"provider": provider, "file": filename, "sha256": digest}
    return entries


def load_registry(path: Path = REGISTRY_FILE) -> list[dict[str, Any]]:
    # UniqueKeyLoader subclasses SafeLoader and only tightens mapping-key handling.
    data = yaml.load(path.read_text(encoding="utf-8"), Loader=UniqueKeyLoader) or {}  # noqa: S506
    if not isinstance(data, dict) or data.get("version") != 1:
        raise ValueError(f"Invalid registry document: {path}")
    targets = data.get("targets") or []
    if not isinstance(targets, list):
        raise ValueError(f"Invalid registry targets: {path}")
    validated: list[dict[str, Any]] = []
    providers: set[str] = set()
    for index, target in enumerate(targets, start=1):
        if not isinstance(target, dict):
            raise ValueError(f"{path}:{index}: registry target must be a mapping")
        provider = safe_module_name(target.get("provider", ""))
        if provider in providers:
            raise ValueError(f"{path}:{index}: duplicate provider {provider}")
        providers.add(provider)
        expected_crawler = f"Crawler/generated_yaml/{provider}.py"
        if target.get("crawler") != expected_crawler:
            raise ValueError(f"{path}:{index}: crawler must be {expected_crawler}")
        arguments = target.get("arguments")
        if not isinstance(arguments, list) or not all(isinstance(argument, str) and argument for argument in arguments):
            raise ValueError(f"{path}:{index}: arguments must be a list of non-empty strings")
        if arguments.count("--save-db") != 1 or any(
            argument == "--all" or argument == "--write-registry" or argument.startswith("--provider")
            for argument in arguments
        ):
            raise ValueError(f"{path}:{index}: arguments violate the fixed-provider execution policy")
        if arguments.count("--per-target-limit") != 1:
            raise ValueError(f"{path}:{index}: arguments must declare exactly one --per-target-limit")
        limit_index = arguments.index("--per-target-limit")
        try:
            per_target_limit = int(arguments[limit_index + 1])
        except (IndexError, TypeError, ValueError) as exc:
            raise ValueError(f"{path}:{index}: --per-target-limit must have an integer value") from exc
        partial_opt_in = arguments.count("--allow-partial-save")
        if (per_target_limit > 0 and partial_opt_in != 1) or (per_target_limit == 0 and partial_opt_in != 0):
            raise ValueError(f"{path}:{index}: partial-save opt-in does not match --per-target-limit")
        try:
            command = shlex.split(str(target.get("command") or ""), posix=True)
        except ValueError as exc:
            raise ValueError(f"{path}:{index}: command is invalid") from exc
        if command != ["python", "-X", "utf8", expected_crawler, *arguments]:
            raise ValueError(f"{path}:{index}: command and arguments differ")
        validated.append(target)
    return validated


def atomic_write_text(path: Path, content: str) -> None:
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
            temporary_path = Path(handle.name)
        os.replace(temporary_path, path)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def write_wrappers(targets: list[dict[str, Any]], output_dir: Path = OUTPUT_DIR) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = output_dir / MANIFEST_FILE.name
    previous_manifest = load_manifest(manifest_path)

    generated: dict[str, str] = {"__init__.py": ""}
    seen_modules: set[str] = set()
    for target in targets:
        provider = str(target["provider"]).strip().upper()
        module_name = safe_module_name(provider)
        if module_name in seen_modules:
            raise ValueError(f"Duplicate provider/module in registry: {provider}")
        seen_modules.add(module_name)
        name = f"{module_name}.py"
        content = WRAPPER_TEMPLATE.format(provider=provider)
        compile(content, name, "exec")
        generated[name] = content

    with tempfile.TemporaryDirectory(prefix=".generated-yaml-stage-", dir=output_dir.parent) as stage_name:
        stage = Path(stage_name)
        for name, content in generated.items():
            (stage / name).write_text(content, encoding="utf-8", newline="\n")
        staged_names = {path.name for path in stage.glob("*.py")}
        if staged_names != set(generated):
            raise RuntimeError("Generated wrapper staging verification failed")
        for name, expected_content in generated.items():
            staged_content = (stage / name).read_text(encoding="utf-8")
            if staged_content != expected_content:
                raise RuntimeError(f"Generated wrapper staging content mismatch: {name}")
        for name in sorted(generated):
            atomic_write_text(output_dir / name, (stage / name).read_text(encoding="utf-8"))

    expected = set(generated)
    for name, expected_content in generated.items():
        path = output_dir / name
        if not path.is_file() or path.read_text(encoding="utf-8") != expected_content:
            raise RuntimeError(f"Generated wrapper post-write verification failed: {name}")
    for provider, entry in previous_manifest.items():
        if entry["file"] in expected:
            continue
        path = output_dir / entry["file"]
        if not path.exists():
            continue
        content = path.read_text(encoding="utf-8")
        digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
        if digest != entry["sha256"] or not is_managed_wrapper_content(content):
            raise RuntimeError(f"Refusing to delete modified generated wrapper: {path.name}")
        path.unlink()

    manifest_entries = [
        {
            "provider": name.removesuffix(".py"),
            "file": name,
            "sha256": hashlib.sha256(generated[name].encode("utf-8")).hexdigest(),
        }
        for name in sorted(expected - {"__init__.py"})
    ]
    manifest_document = {
        "version": MANIFEST_VERSION,
        "generator": "tools/generate_registry_crawler_files.py",
        "wrappers": manifest_entries,
    }
    atomic_write_text(manifest_path, yaml.safe_dump(manifest_document, allow_unicode=True, sort_keys=False))
    loaded_manifest = load_manifest(manifest_path)
    if list(loaded_manifest.values()) != manifest_entries:
        raise RuntimeError("Generated wrapper manifest post-write verification failed")
    return [output_dir / name for name in sorted(expected - {"__init__.py"})]


def main() -> int:
    targets = load_registry()
    written = write_wrappers(targets)
    print(f"registry={REGISTRY_FILE}")
    print(f"output_dir={OUTPUT_DIR}")
    print(f"wrappers={len(written)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
